export const BRAND = "NORVANA";
export const ADMIN_PASSWORD = "norvana";
export const FREE_SHIPPING_THRESHOLD = 75;

export const SAMPLE_PRODUCTS = [
  {
    name: "Midnight Orchid Candle",
    slug: "midnight-orchid-candle",
    description: "Hand-poured soy candle with notes of orchid, vanilla, and sandalwood. Burns for 60+ hours.",
    price: 34.00,
    compareAtPrice: 42.00,
    niche: "home-fragrance",
    volumeNumber: 1,
    status: "active",
    images: ["/images/products/candle-1.jpg"],
    rating: 4.8,
    reviewCount: 124,
    inventory: 85,
    tags: ["candle", "home", "fragrance", "bestseller"],
  },
  {
    name: "Ceramic Pour-Over Set",
    slug: "ceramic-pour-over-set",
    description: "Artisan-crafted ceramic dripper and carafe set. Makes the perfect cup every time.",
    price: 68.00,
    compareAtPrice: 85.00,
    niche: "kitchen",
    volumeNumber: 1,
    status: "active",
    images: ["/images/products/pourover-1.jpg"],
    rating: 4.9,
    reviewCount: 89,
    inventory: 42,
    tags: ["coffee", "kitchen", "ceramic", "bestseller"],
  },
  {
    name: "Linen Throw Blanket",
    slug: "linen-throw-blanket",
    description: "Stonewashed French linen throw in oatmeal. Softens with every wash.",
    price: 120.00,
    compareAtPrice: 155.00,
    niche: "home-decor",
    volumeNumber: 1,
    status: "active",
    images: ["/images/products/linen-1.jpg"],
    rating: 4.7,
    reviewCount: 67,
    inventory: 33,
    tags: ["linen", "throw", "home", "cozy"],
  },
  {
    name: "Japanese Incense Set",
    slug: "japanese-incense-set",
    description: "Premium hinoki and cedarwood incense sticks with brass holder. 50 sticks included.",
    price: 28.00,
    compareAtPrice: null,
    niche: "home-fragrance",
    volumeNumber: 1,
    status: "active",
    images: ["/images/products/incense-1.jpg"],
    rating: 4.6,
    reviewCount: 203,
    inventory: 150,
    tags: ["incense", "japanese", "fragrance", "new"],
  },
  {
    name: "Minimalist Desk Organizer",
    slug: "minimalist-desk-organizer",
    description: "Walnut and brass desk organizer with pen holder, card slot, and cable management.",
    price: 54.00,
    compareAtPrice: 65.00,
    niche: "workspace",
    volumeNumber: 2,
    status: "active",
    images: ["/images/products/desk-1.jpg"],
    rating: 4.5,
    reviewCount: 45,
    inventory: 60,
    tags: ["desk", "organizer", "workspace", "walnut"],
  },
  {
    name: "Hand-Thrown Mug Set",
    slug: "hand-thrown-mug-set",
    description: "Set of 2 stoneware mugs with reactive glaze. Each piece is uniquely beautiful.",
    price: 42.00,
    compareAtPrice: 56.00,
    niche: "kitchen",
    volumeNumber: 2,
    status: "active",
    images: ["/images/products/mug-1.jpg"],
    rating: 4.8,
    reviewCount: 156,
    inventory: 72,
    tags: ["mugs", "stoneware", "kitchen", "bestseller"],
  },
  {
    name: "Botanical Print Set",
    slug: "botanical-print-set",
    description: "Set of 3 archival quality botanical prints on 300gsm cotton paper. Unframed, 8x10\".",
    price: 38.00,
    compareAtPrice: null,
    niche: "art",
    volumeNumber: 2,
    status: "active",
    images: ["/images/products/print-1.jpg"],
    rating: 4.4,
    reviewCount: 31,
    inventory: 95,
    tags: ["art", "botanical", "print", "wall-decor"],
  },
  {
    name: "Copper Watering Can",
    slug: "copper-watering-can",
    description: "Solid copper watering can with long spout. Develops a beautiful patina over time.",
    price: 78.00,
    compareAtPrice: 95.00,
    niche: "garden",
    volumeNumber: 3,
    status: "active",
    images: ["/images/products/watering-1.jpg"],
    rating: 4.9,
    reviewCount: 78,
    inventory: 25,
    tags: ["garden", "copper", "watering", "new"],
  },
  {
    name: "Wool Meditation Cushion",
    slug: "wool-meditation-cushion",
    description: "Buckwheat hull filled zafu with hand-woven wool cover. Available in natural and indigo.",
    price: 65.00,
    compareAtPrice: null,
    niche: "wellness",
    volumeNumber: 3,
    status: "active",
    images: ["/images/products/cushion-1.jpg"],
    rating: 4.7,
    reviewCount: 92,
    inventory: 48,
    tags: ["meditation", "wool", "wellness", "mindfulness"],
  },
  {
    name: "Artisan Soap Trio",
    slug: "artisan-soap-trio",
    description: "Cold-process soaps in lavender, eucalyptus, and charcoal. Vegan and palm-oil free.",
    price: 24.00,
    compareAtPrice: 30.00,
    niche: "bath",
    volumeNumber: 3,
    status: "active",
    images: ["/images/products/soap-1.jpg"],
    rating: 4.6,
    reviewCount: 341,
    inventory: 200,
    tags: ["soap", "bath", "vegan", "bestseller"],
  },
  {
    name: "Leather Journal",
    slug: "leather-journal",
    description: "Full-grain vegetable-tanned leather journal with 240 pages of cream-colored paper.",
    price: 48.00,
    compareAtPrice: 60.00,
    niche: "stationery",
    volumeNumber: 1,
    status: "active",
    images: ["/images/products/journal-1.jpg"],
    rating: 4.8,
    reviewCount: 167,
    inventory: 55,
    tags: ["journal", "leather", "stationery", "writing"],
  },
  {
    name: "Brass Plant Mister",
    slug: "brass-plant-mister",
    description: "Vintage-style brass plant mister with fine mist spray. 10oz capacity.",
    price: 32.00,
    compareAtPrice: null,
    niche: "garden",
    volumeNumber: 2,
    status: "active",
    images: ["/images/products/mister-1.jpg"],
    rating: 4.5,
    reviewCount: 88,
    inventory: 110,
    tags: ["garden", "brass", "plants", "mister"],
  },
];

export const SAMPLE_VOLUMES = [
  {
    volumeNumber: 1,
    niche: "Home & Sanctuary",
    description: "Curated essentials for creating your perfect home sanctuary. Fragrances, textiles, and daily rituals.",
    heroImage: "/images/volumes/vol-1.jpg",
    startDate: "2024-01-01",
    endDate: "2024-04-30",
    isActive: false,
  },
  {
    volumeNumber: 2,
    niche: "Kitchen & Craft",
    description: "Handmade tools and artisan pieces for the modern kitchen. Beauty meets function.",
    heroImage: "/images/volumes/vol-2.jpg",
    startDate: "2024-05-01",
    endDate: "2024-08-31",
    isActive: false,
  },
  {
    volumeNumber: 3,
    niche: "Garden & Wellness",
    description: "Tools for tending your garden and your mind. Nature-inspired pieces for modern living.",
    heroImage: "/images/volumes/vol-3.jpg",
    startDate: "2024-09-01",
    endDate: "2024-12-31",
    isActive: true,
  },
];

export const SAMPLE_SUPPLIERS = [
  { name: "Epoch Candle Co.", url: "https://epochcandles.com", contactEmail: "wholesale@epochcandles.com", notes: "MOQ 50 units. Lead time 2-3 weeks." },
  { name: "Hasami Porcelain", url: "https://hasami-porcelain.com", contactEmail: "orders@hasami.jp", notes: "Japanese porcelain. Ships from LA warehouse." },
  { name: "Fog Linen Work", url: "https://foglinenwork.com", contactEmail: "trade@foglinenwork.com", notes: "Lithuanian linen. Seasonal collections." },
  { name: "Nippon Kodo", url: "https://nipponkodo.com", contactEmail: "export@nipponkodo.co.jp", notes: "Japanese incense manufacturer since 1575." },
  { name: "Grovemade", url: "https://grovemade.com", contactEmail: "wholesale@grovemade.com", notes: "Portland-based. Desk accessories and organizers." },
  { name: "East Fork Pottery", url: "https://eastfork.com", contactEmail: "wholesale@eastfork.com", notes: "Asheville NC. Reactive glazes. Popular." },
  { name: "Rifle Paper Co.", url: "https://riflepaperco.com", contactEmail: "wholesale@riflepaperco.com", notes: "Botanical prints and stationery." },
  { name: "Haws Watering Cans", url: "https://haws.co.uk", contactEmail: "trade@haws.co.uk", notes: "British heritage brand. Copper and zinc." },
  { name: "Organic Cushions Co.", url: "https://organiccushions.com", contactEmail: "info@organiccushions.com", notes: "Buckwheat and kapok fills. Fair trade." },
  { name: "Herbivore Botanicals", url: "https://herbivorebotanicals.com", contactEmail: "wholesale@herbivore.com", notes: "Natural bath & body. Based in Seattle." },
  { name: "Leuchtturm1917", url: "https://leuchtturm1917.com", contactEmail: "wholesale@leuchtturm.com", notes: "German-made notebooks. Multiple formats." },
  { name: "Schoolhouse", url: "https://schoolhouse.com", contactEmail: "trade@schoolhouse.com", notes: "Lighting and home goods. Portland OR." },
  { name: "Vitruvi", url: "https://vitruvi.com", contactEmail: "wholesale@vitruvi.com", notes: "Essential oil diffusers and blends." },
  { name: "Sabre Paris", url: "https://sabre.fr", contactEmail: "export@sabre.fr", notes: "French flatware and cutlery. Bold colors." },
  { name: "HAY Design", url: "https://hay.dk", contactEmail: "wholesale@hay.dk", notes: "Danish design. Home accessories and furniture." },
];

export const SCOUT_PRODUCTS = [
  { name: "Ceramic Oil Diffuser", trendScore: 92, margin: "68%", supplierCount: 4, category: "Home Fragrance", badge: "bestseller" },
  { name: "Handwoven Storage Basket", trendScore: 87, margin: "72%", supplierCount: 6, category: "Organization", badge: "new" },
  { name: "Cork Yoga Mat", trendScore: 85, margin: "55%", supplierCount: 3, category: "Wellness", badge: "new" },
  { name: "Brass Candle Snuffer", trendScore: 81, margin: "78%", supplierCount: 5, category: "Home Decor", badge: "bestseller" },
  { name: "Linen Apron", trendScore: 79, margin: "62%", supplierCount: 7, category: "Kitchen", badge: null },
  { name: "Recycled Glass Vase", trendScore: 76, margin: "65%", supplierCount: 4, category: "Home Decor", badge: "new" },
  { name: "Shea Butter Hand Cream", trendScore: 74, margin: "71%", supplierCount: 8, category: "Bath & Body", badge: null },
  { name: "Wooden Cutting Board", trendScore: 71, margin: "58%", supplierCount: 5, category: "Kitchen", badge: "bestseller" },
];

export const SAMPLE_REVIEWS = [
  { author: "Sarah M.", rating: 5, title: "Absolutely love it!", body: "The quality exceeded my expectations. Will definitely be ordering more.", verified: true },
  { author: "James K.", rating: 4, title: "Great quality", body: "Beautiful craftsmanship. Shipping was fast too.", verified: true },
  { author: "Emily R.", rating: 5, title: "Perfect gift", body: "Bought this as a gift and they loved it. Packaging was gorgeous.", verified: true },
  { author: "Michael D.", rating: 4, title: "Worth every penny", body: "High quality materials and attention to detail. Very impressed.", verified: false },
  { author: "Lisa T.", rating: 5, title: "My new favorite", body: "This has become an essential part of my daily routine. So well made.", verified: true },
];
