export type AffiliatePriority = "APPLY_FIRST" | "SELECTIVE" | "LATER";
export type AffiliateCategory =
  | "GENERAL"
  | "ELECTRONICS"
  | "GAMING"
  | "FASHION"
  | "LUXURY"
  | "BEAUTY"
  | "PETS"
  | "HOME"
  | "OUTDOORS"
  | "FAMILY"
  | "MEDIA";

export type AffiliateProgramEntry = {
  slug: string;
  name: string;
  categories: AffiliateCategory[];
  website: string;
  applyUrl: string;
  network: string;
  priority: AffiliatePriority;
  coverage: string;
  economics: string;
  why: string;
  caution?: string;
};

export const AFFILIATE_PROGRAMS: AffiliateProgramEntry[] = [
  {
    slug: "walmart",
    name: "Walmart Affiliate Program",
    categories: ["GENERAL", "ELECTRONICS", "FAMILY", "HOME", "BEAUTY", "PETS"],
    website: "https://www.walmart.com/",
    applyUrl: "https://affiliates.walmart.com/",
    network: "Walmart Affiliate Platform",
    priority: "APPLY_FIRST",
    coverage: "Huge everyday catalog: groceries-adjacent household goods, electronics, toys, beauty, pets, home, auto, and more.",
    economics: "Broad basket coverage; commissions vary by category.",
    why: "Excellent everyday anchor because one program covers many Acre Era categories.",
  },
  {
    slug: "target",
    name: "Target Partners",
    categories: ["GENERAL", "FAMILY", "HOME", "BEAUTY", "ELECTRONICS", "PETS"],
    website: "https://www.target.com/",
    applyUrl: "https://partners.target.com/",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "More than one million products across family, home, beauty, tech, toys, pets, and everyday goods.",
    economics: "Target currently advertises commissions up to 8% with a 7-day attribution window.",
    why: "Strong family/everyday fit and clean mainstream brand trust.",
  },
  {
    slug: "ebay",
    name: "eBay Partner Network",
    categories: ["GENERAL", "ELECTRONICS", "GAMING", "FASHION", "LUXURY", "FAMILY"],
    website: "https://www.ebay.com/",
    applyUrl: "https://partnernetwork.ebay.com/",
    network: "eBay Partner Network",
    priority: "APPLY_FIRST",
    coverage: "Massive new/pre-owned catalog including electronics, gaming, sneakers, watches, collectibles, luxury, and hard-to-find goods.",
    economics: "Category-based commission model tied to qualified eBay transactions.",
    why: "One of the best bridges between everyday, collectible, tech, resale, and premium inventory.",
  },
  {
    slug: "amazon",
    name: "Amazon Associates",
    categories: ["GENERAL", "ELECTRONICS", "FAMILY", "HOME", "BEAUTY", "PETS", "GAMING"],
    website: "https://www.amazon.com/",
    applyUrl: "https://associates.amazon.com/signup",
    network: "Amazon Associates",
    priority: "SELECTIVE",
    coverage: "Near-universal product breadth plus Creators API access after Associates onboarding.",
    economics: "Commission rates vary significantly by category.",
    why: "Useful coverage/fallback, but Acre Era should not become an Amazon link farm.",
    caution: "Use for gaps and high-converting utility, not as the identity of the storefront.",
  },
  {
    slug: "best-buy",
    name: "Best Buy Affiliate / Creator Program",
    categories: ["ELECTRONICS", "GAMING", "FAMILY"],
    website: "https://www.bestbuy.com/",
    applyUrl: "https://www.bestbuy.com/site/misc/best-buy-affiliate-program/pcmcat198500050002.c?id=pcmcat198500050002",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Phones, computers, TVs, appliances, gaming, smart home, audio, cameras, and accessories.",
    economics: "Commission on qualifying BestBuy.com purchases; payout terms vary.",
    why: "Core electronics/phone/gaming anchor with customer trust and current product depth.",
  },
  {
    slug: "newegg",
    name: "Newegg Affiliate Program",
    categories: ["ELECTRONICS", "GAMING"],
    website: "https://www.newegg.com/",
    applyUrl: "https://www.newegg.com/promotions/affiliate_program/affiliate.html",
    network: "Newegg Affiliate",
    priority: "APPLY_FIRST",
    coverage: "PC hardware, gaming, electronics, smart home, drones, tech toys, and health tech.",
    economics: "Free to join; commission on referred sales.",
    why: "Excellent specialist catalog where Best Buy is too mainstream or shallow.",
  },
  {
    slug: "gamestop",
    name: "GameStop Affiliate Program",
    categories: ["GAMING", "FAMILY", "ELECTRONICS"],
    website: "https://www.gamestop.com/",
    applyUrl: "https://www.gamestop.com/affiliate.html",
    network: "Third-party affiliate manager",
    priority: "APPLY_FIRST",
    coverage: "Consoles, games, accessories, collectibles, toys, used/pre-owned gaming products.",
    economics: "Free to join; commission on qualifying click-through purchases.",
    why: "Dedicated gaming anchor instead of forcing gaming through general retailers.",
  },
  {
    slug: "microsoft",
    name: "Microsoft Affiliate Program",
    categories: ["ELECTRONICS", "GAMING"],
    website: "https://www.microsoft.com/",
    applyUrl: "https://partner.microsoft.com/en-us/explore/consumer",
    network: "Microsoft Partner / Affiliate",
    priority: "SELECTIVE",
    coverage: "Microsoft consumer products, software, Surface, Xbox, accessories, and related offers depending on program availability.",
    economics: "Program terms and commissions depend on the participating consumer offer.",
    why: "Useful direct-brand lane for Microsoft/Xbox when economics beat general retailers.",
  },
  {
    slug: "nike",
    name: "Nike Affiliate Program",
    categories: ["FASHION", "OUTDOORS"],
    website: "https://www.nike.com/",
    applyUrl: "https://www.nike.com/help/a/nike-affiliate-program",
    network: "CJ Affiliate",
    priority: "APPLY_FIRST",
    coverage: "Footwear, apparel, sport, lifestyle, and accessories.",
    economics: "Nike currently advertises up to 15% on valid U.S. sales for qualifying partners/products; 7-day cookie.",
    why: "Strong $100–$250 footwear/apparel lane and recognizable traffic driver.",
  },
  {
    slug: "adidas",
    name: "adidas Affiliate Program",
    categories: ["FASHION", "OUTDOORS"],
    website: "https://www.adidas.com/",
    applyUrl: "https://www.adidas.com/us/help/us-company-information/what-is-our-affiliate-program",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Athletic footwear, fashion, accessories, and sport.",
    economics: "Commission on qualifying sales; terms visible after partner application.",
    why: "Natural complement to Nike and a useful athletic/style lane.",
  },
  {
    slug: "nordstrom",
    name: "Nordstrom Affiliate Program",
    categories: ["FASHION", "LUXURY", "BEAUTY"],
    website: "https://www.nordstrom.com/",
    applyUrl: "https://www.nordstrom.com/browse/affiliate-program",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Designer fashion, shoes, handbags, beauty, accessories, and premium department-store inventory.",
    economics: "Competitive commissions; creator and publisher tracks.",
    why: "Excellent bridge between everyday premium and true luxury without making Acre Era feel like a resale-only site.",
  },
  {
    slug: "farfetch",
    name: "FARFETCH Affiliate Programme",
    categories: ["LUXURY", "FASHION"],
    website: "https://www.farfetch.com/",
    applyUrl: "https://www.farfetch.com/am/pag1987.aspx/",
    network: "FARFETCH Affiliate",
    priority: "APPLY_FIRST",
    coverage: "Luxury designer fashion, shoes, handbags, accessories, and global boutique inventory.",
    economics: "Commission on approved global sales; 30-day cookie; daily product feeds.",
    why: "Best high-end editorial/luxury lane in the starter portfolio.",
  },
  {
    slug: "stockx",
    name: "StockX Affiliate Program",
    categories: ["FASHION", "LUXURY", "GAMING"],
    website: "https://stockx.com/",
    applyUrl: "https://stockx.com/news/en-us/stockx-affiliate-program/",
    network: "Impact",
    priority: "SELECTIVE",
    coverage: "Sneakers, streetwear, collectibles, watches, handbags, and resale-market product.",
    economics: "Current official pages describe category/new-vs-returning-customer commissions and 15-day attribution.",
    why: "Useful for culturally relevant premium/resale items that fit Era storytelling.",
    caution: "Keep separate from direct-brand inventory so customers understand the marketplace route.",
  },
  {
    slug: "sephora",
    name: "Sephora Affiliate Program",
    categories: ["BEAUTY", "LUXURY"],
    website: "https://www.sephora.com/",
    applyUrl: "https://www.sephora.com/beauty/affiliates/",
    network: "Rakuten Advertising",
    priority: "APPLY_FIRST",
    coverage: "Beauty, skincare, fragrance, haircare, and luxury beauty across 200+ brands.",
    economics: "Commission on qualifying products; Sephora states no brand restrictions for its affiliate catalog.",
    why: "Acre Era needs a serious beauty anchor rather than random dropship cosmetics.",
  },
  {
    slug: "ulta",
    name: "Ulta Beauty Affiliate Program",
    categories: ["BEAUTY"],
    website: "https://www.ulta.com/",
    applyUrl: "https://www.ulta.com/company/affiliate",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Mass and prestige beauty, skincare, haircare, tools, fragrance, and wellness.",
    economics: "Free to apply; commission on referred qualifying sales.",
    why: "Pairs well with Sephora while reaching more mass-market beauty shoppers.",
  },
  {
    slug: "chewy",
    name: "Chewy Affiliate Program",
    categories: ["PETS"],
    website: "https://www.chewy.com/",
    applyUrl: "https://www.chewy.com/app/content/affiliate",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Food, treats, toys, health, supplies, and specialty pet categories.",
    economics: "Commission on eligible new and existing-customer orders.",
    why: "Probably the strongest dedicated pet anchor for repeat-purchase behavior.",
  },
  {
    slug: "petco",
    name: "Petco Affiliate Program",
    categories: ["PETS"],
    website: "https://www.petco.com/",
    applyUrl: "https://www.petco.com/affiliate",
    network: "Impact",
    priority: "SELECTIVE",
    coverage: "Pet food, supplies, services, health, grooming-related products, and accessories.",
    economics: "Free/easy application; commission on valid referred sales.",
    why: "Good second pet source and useful comparison against Chewy economics.",
  },
  {
    slug: "lowes",
    name: "Lowe's Creator Program",
    categories: ["HOME", "FAMILY"],
    website: "https://www.lowes.com/",
    applyUrl: "https://www.lowes.com/l/creator/joinlowescreator",
    network: "Lowe's Creator",
    priority: "APPLY_FIRST",
    coverage: "Home improvement, appliances, tools, garden, outdoor living, furniture, and project supplies.",
    economics: "Lowe's currently advertises up to 25% by product category with a 30-day attribution window.",
    why: "Very attractive home-category economics if Acre Era qualifies.",
  },
  {
    slug: "home-depot",
    name: "The Home Depot Affiliate / Creator Program",
    categories: ["HOME", "FAMILY"],
    website: "https://www.homedepot.com/",
    applyUrl: "https://creators.homedepot.com/splash",
    network: "Home Depot Creator",
    priority: "APPLY_FIRST",
    coverage: "Home improvement, appliances, tools, garden, furniture, outdoor living, smart home.",
    economics: "Creator program currently advertises 8% on eligible sales.",
    why: "Strong trusted home anchor and natural fit for homeowner/family shoppers.",
  },
  {
    slug: "wayfair",
    name: "Wayfair Affiliate Program",
    categories: ["HOME"],
    website: "https://www.wayfair.com/",
    applyUrl: "https://www.wayfair.com/help/article/Affiliate-Help-Center-E3050",
    network: "Wayfair Affiliate",
    priority: "SELECTIVE",
    coverage: "Furniture, decor, kitchen, bedding, outdoor, and broad home assortment.",
    economics: "Affiliate program exists; validate current payout terms during application.",
    why: "Useful deeper furniture/decor lane if Home Depot/Lowe's leave category gaps.",
  },
  {
    slug: "rei",
    name: "REI Co-op Affiliate Program",
    categories: ["OUTDOORS", "FASHION", "FAMILY"],
    website: "https://www.rei.com/",
    applyUrl: "https://www.rei.com/help?a=Become-an-REI-Co-op-Affiliate---id--SnToxfZRRI-o6A7lkasoWA",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Outdoor gear, footwear, apparel, bikes/e-bikes, travel, camping, fitness, and memberships.",
    economics: "REI cites competitive commission and approximately $160 average order value.",
    why: "Perfect bridge between the open-road visual story and actual products people buy.",
  },
  {
    slug: "lego",
    name: "LEGO.com Affiliate Program",
    categories: ["FAMILY", "GAMING"],
    website: "https://www.lego.com/en-us/",
    applyUrl: "https://www.lego.com/en-us/page/affiliate-program",
    network: "LEGO affiliate network partners",
    priority: "SELECTIVE",
    coverage: "LEGO sets, exclusives, collectibles, gifts, and family/kids products.",
    economics: "Commission on validated LEGO.com sales.",
    why: "Strong family/collectible lane that can work with holiday and Era storytelling.",
  },
  {
    slug: "apple-services",
    name: "Apple Services Performance Partners",
    categories: ["MEDIA"],
    website: "https://www.apple.com/",
    applyUrl: "https://performance-partners.apple.com/home",
    network: "Partnerize",
    priority: "LATER",
    coverage: "Apple Music, Apple TV, Podcasts, Books, movies/TV and related Apple services — not a general iPhone/Mac hardware affiliate program.",
    economics: "Apple lists 30-day attribution for several services and 7% on qualifying TV/movies and books; acceptance is selective.",
    why: "Potential media/Era tie-in later, but it does not solve our phone/device merchandising need.",
    caution: "Do not treat this as a hardware affiliate lane.",
  },
  {
    slug: "samsung-referral",
    name: "Samsung Referral Program",
    categories: ["ELECTRONICS"],
    website: "https://www.samsung.com/us/",
    applyUrl: "https://www.samsung.com/us/shop/referral-deals/",
    network: "Samsung Rewards",
    priority: "LATER",
    coverage: "Samsung phones/electronics referral purchases.",
    economics: "Current public referral program rewards advocates in Samsung Rewards points rather than normal cash affiliate commission.",
    why: "Not attractive enough to make a core Acre Era revenue lane unless Samsung offers us a stronger partner arrangement later.",
    caution: "Rewards points are not the same business model as cash affiliate revenue.",
  },
];
