export type AffiliatePriority = "APPLY_FIRST" | "SELECTIVE" | "LATER";
export type AffiliateCategory =
  | "GENERAL"
  | "ELECTRONICS"
  | "GAMING"
  | "FASHION"
  | "LUXURY"
  | "BEAUTY"
  | "PETS"
  | "HOME"
  | "OUTDOORS"
  | "FAMILY"
  | "MEDIA";

export type AffiliateProgramEntry = {
  slug: string;
  name: string;
  categories: AffiliateCategory[];
  website: string;
  applyUrl: string;
  network: string;
  priority: AffiliatePriority;
  coverage: string;
  economics: string;
  why: string;
  caution?: string;
};

export const AFFILIATE_PROGRAMS: AffiliateProgramEntry[] = [
  {
    slug: "walmart",
    name: "Walmart Affiliate Program",
    categories: ["GENERAL", "ELECTRONICS", "FAMILY", "HOME", "BEAUTY", "PETS"],
    website: "https://www.walmart.com/",
    applyUrl: "https://affiliates.walmart.com/",
    network: "Walmart Affiliate Platform",
    priority: "APPLY_FIRST",
    coverage: "Huge everyday catalog: groceries-adjacent household goods, electronics, toys, beauty, pets, home, auto, and more.",
    economics: "Broad basket coverage; commissions vary by category.",
    why: "Excellent everyday anchor because one program covers many Acre Era categories.",
  },
  {
    slug: "target",
    name: "Target Partners",
    categories: ["GENERAL", "FAMILY", "HOME", "BEAUTY", "ELECTRONICS", "PETS"],
    website: "https://www.target.com/",
    applyUrl: "https://partners.target.com/",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "More than one million products across family, home, beauty, tech, toys, pets, and everyday goods.",
    economics: "Target currently advertises commissions up to 8% with a 7-day attribution window.",
    why: "Strong family/everyday fit and clean mainstream brand trust.",
  },
  {
    slug: "ebay",
    name: "eBay Partner Network",
    categories: ["GENERAL", "ELECTRONICS", "GAMING", "FASHION", "LUXURY", "FAMILY"],
    website: "https://www.ebay.com/",
    applyUrl: "https://partnernetwork.ebay.com/",
    network: "eBay Partner Network",
    priority: "APPLY_FIRST",
    coverage: "Massive new/pre-owned catalog including electronics, gaming, sneakers, watches, collectibles, luxury, and hard-to-find goods.",
    economics: "Category-based commission model tied to qualified eBay transactions.",
    why: "One of the best bridges between everyday, collectible, tech, resale, and premium inventory.",
  },
  {
    slug: "amazon",
    name: "Amazon Associates",
    categories: ["GENERAL", "ELECTRONICS", "FAMILY", "HOME", "BEAUTY", "PETS", "GAMING"],
    website: "https://www.amazon.com/",
    applyUrl: "https://associates.amazon.com/signup",
    network: "Amazon Associates",
    priority: "SELECTIVE",
    coverage: "Near-universal product breadth plus Creators API access after Associates onboarding.",
    economics: "Commission rates vary significantly by category.",
    why: "Useful coverage/fallback, but Acre Era should not become an Amazon link farm.",
    caution: "Use for gaps and high-converting utility, not as the identity of the storefront.",
  },
  {
    slug: "best-buy",
    name: "Best Buy Affiliate / Creator Program",
    categories: ["ELECTRONICS", "GAMING", "FAMILY"],
    website: "https://www.bestbuy.com/",
    applyUrl: "https://www.bestbuy.com/site/misc/best-buy-affiliate-program/pcmcat198500050002.c?id=pcmcat198500050002",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Phones, computers, TVs, appliances, gaming, smart home, audio, cameras, and accessories.",
    economics: "Commission on qualifying BestBuy.com purchases; payout terms vary.",
    why: "Core electronics/phone/gaming anchor with customer trust and current product depth.",
  },
  {
    slug: "newegg",
    name: "Newegg Affiliate Program",
    categories: ["ELECTRONICS", "GAMING"],
    website: "https://www.newegg.com/",
    applyUrl: "https://www.newegg.com/promotions/affiliate_program/affiliate.html",
    network: "Newegg Affiliate",
    priority: "APPLY_FIRST",
    coverage: "PC hardware, gaming, electronics, smart home, drones, tech toys, and health tech.",
    economics: "Free to join; commission on referred sales.",
    why: "Excellent specialist catalog where Best Buy is too mainstream or shallow.",
  },
  {
    slug: "gamestop",
    name: "GameStop Affiliate Program",
    categories: ["GAMING", "FAMILY", "ELECTRONICS"],
    website: "https://www.gamestop.com/",
    applyUrl: "https://www.gamestop.com/affiliate.html",
    network: "Third-party affiliate manager",
    priority: "APPLY_FIRST",
    coverage: "Consoles, games, accessories, collectibles, toys, used/pre-owned gaming products.",
    economics: "Free to join; commission on qualifying click-through purchases.",
    why: "Dedicated gaming anchor instead of forcing gaming through general retailers.",
  },
  {
    slug: "microsoft",
    name: "Microsoft Affiliate Program",
    categories: ["ELECTRONICS", "GAMING"],
    website: "https://www.microsoft.com/",
    applyUrl: "https://partner.microsoft.com/en-us/explore/consumer",
    network: "Microsoft Partner / Affiliate",
    priority: "SELECTIVE",
    coverage: "Microsoft consumer products, software, Surface, Xbox, accessories, and related offers depending on program availability.",
    economics: "Program terms and commissions depend on the participating consumer offer.",
    why: "Useful direct-brand lane for Microsoft/Xbox when economics beat general retailers.",
  },
  {
    slug: "nike",
    name: "Nike Affiliate Program",
    categories: ["FASHION", "OUTDOORS"],
    website: "https://www.nike.com/",
    applyUrl: "https://www.nike.com/help/a/nike-affiliate-program",
    network: "CJ Affiliate",
    priority: "APPLY_FIRST",
    coverage: "Footwear, apparel, sport, lifestyle, and accessories.",
    economics: "Nike currently advertises up to 15% on valid U.S. sales for qualifying partners/products; 7-day cookie.",
    why: "Strong $100–$250 footwear/apparel lane and recognizable traffic driver.",
  },
  {
    slug: "adidas",
    name: "adidas Affiliate Program",
    categories: ["FASHION", "OUTDOORS"],
    website: "https://www.adidas.com/",
    applyUrl: "https://www.adidas.com/us/help/us-company-information/what-is-our-affiliate-program",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Athletic footwear, fashion, accessories, and sport.",
    economics: "Commission on qualifying sales; terms visible after partner application.",
    why: "Natural complement to Nike and a useful athletic/style lane.",
  },
  {
    slug: "nordstrom",
    name: "Nordstrom Affiliate Program",
    categories: ["FASHION", "LUXURY", "BEAUTY"],
    website: "https://www.nordstrom.com/",
    applyUrl: "https://www.nordstrom.com/browse/affiliate-program",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Designer fashion, shoes, handbags, beauty, accessories, and premium department-store inventory.",
    economics: "Competitive commissions; creator and publisher tracks.",
    why: "Excellent bridge between everyday premium and true luxury without making Acre Era feel like a resale-only site.",
  },
  {
    slug: "farfetch",
    name: "FARFETCH Affiliate Programme",
    categories: ["LUXURY", "FASHION"],
    website: "https://www.farfetch.com/",
    applyUrl: "https://www.farfetch.com/am/pag1987.aspx/",
    network: "FARFETCH Affiliate",
    priority: "APPLY_FIRST",
    coverage: "Luxury designer fashion, shoes, handbags, accessories, and global boutique inventory.",
    economics: "Commission on approved global sales; 30-day cookie; daily product feeds.",
    why: "Best high-end editorial/luxury lane in the starter portfolio.",
  },
  {
    slug: "stockx",
    name: "StockX Affiliate Program",
    categories: ["FASHION", "LUXURY", "GAMING"],
    website: "https://stockx.com/",
    applyUrl: "https://stockx.com/news/en-us/stockx-affiliate-program/",
    network: "Impact",
    priority: "SELECTIVE",
    coverage: "Sneakers, streetwear, collectibles, watches, handbags, and resale-market product.",
    economics: "Current official pages describe category/new-vs-returning-customer commissions and 15-day attribution.",
    why: "Useful for culturally relevant premium/resale items that fit Era storytelling.",
    caution: "Keep separate from direct-brand inventory so customers understand the marketplace route.",
  },
  {
    slug: "sephora",
    name: "Sephora Affiliate Program",
    categories: ["BEAUTY", "LUXURY"],
    website: "https://www.sephora.com/",
    applyUrl: "https://www.sephora.com/beauty/affiliates/",
    network: "Rakuten Advertising",
    priority: "APPLY_FIRST",
    coverage: "Beauty, skincare, fragrance, haircare, and luxury beauty across 200+ brands.",
    economics: "Commission on qualifying products; Sephora states no brand restrictions for its affiliate catalog.",
    why: "Acre Era needs a serious beauty anchor rather than random dropship cosmetics.",
  },
  {
    slug: "ulta",
    name: "Ulta Beauty Affiliate Program",
    categories: ["BEAUTY"],
    website: "https://www.ulta.com/",
    applyUrl: "https://www.ulta.com/company/affiliate",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Mass and prestige beauty, skincare, haircare, tools, fragrance, and wellness.",
    economics: "Free to apply; commission on referred qualifying sales.",
    why: "Pairs well with Sephora while reaching more mass-market beauty shoppers.",
  },
  {
    slug: "chewy",
    name: "Chewy Affiliate Program",
    categories: ["PETS"],
    website: "https://www.chewy.com/",
    applyUrl: "https://www.chewy.com/app/content/affiliate",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Food, treats, toys, health, supplies, and specialty pet categories.",
    economics: "Commission on eligible new and existing-customer orders.",
    why: "Probably the strongest dedicated pet anchor for repeat-purchase behavior.",
  },
  {
    slug: "petco",
    name: "Petco Affiliate Program",
    categories: ["PETS"],
    website: "https://www.petco.com/",
    applyUrl: "https://www.petco.com/affiliate",
    network: "Impact",
    priority: "SELECTIVE",
    coverage: "Pet food, supplies, services, health, grooming-related products, and accessories.",
    economics: "Free/easy application; commission on valid referred sales.",
    why: "Good second pet source and useful comparison against Chewy economics.",
  },
  {
    slug: "lowes",
    name: "Lowe's Creator Program",
    categories: ["HOME", "FAMILY"],
    website: "https://www.lowes.com/",
    applyUrl: "https://www.lowes.com/l/creator/joinlowescreator",
    network: "Lowe's Creator",
    priority: "APPLY_FIRST",
    coverage: "Home improvement, appliances, tools, garden, outdoor living, furniture, and project supplies.",
    economics: "Lowe's currently advertises up to 25% by product category with a 30-day attribution window.",
    why: "Very attractive home-category economics if Acre Era qualifies.",
  },
  {
    slug: "home-depot",
    name: "The Home Depot Affiliate / Creator Program",
    categories: ["HOME", "FAMILY"],
    website: "https://www.homedepot.com/",
    applyUrl: "https://creators.homedepot.com/splash",
    network: "Home Depot Creator",
    priority: "APPLY_FIRST",
    coverage: "Home improvement, appliances, tools, garden, furniture, outdoor living, smart home.",
    economics: "Creator program currently advertises 8% on eligible sales.",
    why: "Strong trusted home anchor and natural fit for homeowner/family shoppers.",
  },
  {
    slug: "wayfair",
    name: "Wayfair Affiliate Program",
    categories: ["HOME"],
    website: "https://www.wayfair.com/",
    applyUrl: "https://www.wayfair.com/help/article/Affiliate-Help-Center-E3050",
    network: "Wayfair Affiliate",
    priority: "SELECTIVE",
    coverage: "Furniture, decor, kitchen, bedding, outdoor, and broad home assortment.",
    economics: "Affiliate program exists; validate current payout terms during application.",
    why: "Useful deeper furniture/decor lane if Home Depot/Lowe's leave category gaps.",
  },
  {
    slug: "rei",
    name: "REI Co-op Affiliate Program",
    categories: ["OUTDOORS", "FASHION", "FAMILY"],
    website: "https://www.rei.com/",
    applyUrl: "https://www.rei.com/help?a=Become-an-REI-Co-op-Affiliate---id--SnToxfZRRI-o6A7lkasoWA",
    network: "Impact",
    priority: "APPLY_FIRST",
    coverage: "Outdoor gear, footwear, apparel, bikes/e-bikes, travel, camping, fitness, and memberships.",
    economics: "REI cites competitive commission and approximately $160 average order value.",
    why: "Perfect bridge between the open-road visual story and actual products people buy.",
  },
  {
    slug: "lego",
    name: "LEGO.com Affiliate Program",
    categories: ["FAMILY", "GAMING"],
    website: "https://www.lego.com/en-us/",
    applyUrl: "https://www.lego.com/en-us/page/affiliate-program",
    network: "LEGO affiliate network partners",
    priority: "SELECTIVE",
    coverage: "LEGO sets, exclusives, collectibles, gifts, and family/kids products.",
    economics: "Commission on validated LEGO.com sales.",
    why: "Strong family/collectible lane that can work with holiday and Era storytelling.",
  },
  {
    slug: "apple-services",
    name: "Apple Services Performance Partners",
    categories: ["MEDIA"],
    website: "https://www.apple.com/",
    applyUrl: "https://performance-partners.apple.com/home",
    network: "Partnerize",
    priority: "LATER",
    coverage: "Apple Music, Apple TV, Podcasts, Books, movies/TV and related Apple services — not a general iPhone/Mac hardware affiliate program.",
    economics: "Apple lists 30-day attribution for several services and 7% on qualifying TV/movies and books; acceptance is selective.",
    why: "Potential media/Era tie-in later, but it does not solve our phone/device merchandising need.",
    caution: "Do not treat this as a hardware affiliate lane.",
  },
  {
    slug: "samsung-referral",
    name: "Samsung Referral Program",
    categories: ["ELECTRONICS"],
    website: "https://www.samsung.com/us/",
    applyUrl: "https://www.samsung.com/us/shop/referral-deals/",
    network: "Samsung Rewards",
    priority: "LATER",
    coverage: "Samsung phones/electronics referral purchases.",
    economics: "Current public referral program rewards advocates in Samsung Rewards points rather than normal cash affiliate commission.",
    why: "Not attractive enough to make a core Acre Era revenue lane unless Samsung offers us a stronger partner arrangement later.",
    caution: "Rewards points are not the same business model as cash affiliate revenue.",
  },
];


export type AffiliateNetworkEntry = {
  slug: string;
  name: string;
  applyUrl: string;
  cost: string;
  reach: string;
  examples: string[];
  priority: "APPLY_NOW" | "OPTIONAL";
  note?: string;
};

export const AFFILIATE_NETWORKS: AffiliateNetworkEntry[] = [
  {
    slug: "impact",
    name: "Impact",
    applyUrl: "https://impact.com/get-started/",
    cost: "Free for publishers / creators",
    reach: "Thousands of brands plus a large product marketplace.",
    examples: ["Adidas", "Lenovo", "StockX", "L'Oréal", "Fanatics"],
    priority: "APPLY_NOW",
    note: "Best first network for Acre Era because several of our target brands already use it.",
  },
  {
    slug: "awin",
    name: "Awin",
    applyUrl: "https://www.awin.com/us/publishers",
    cost: "$1 verification deposit, credited back after first tracked sale",
    reach: "30,000+ brands advertised across its global network.",
    examples: ["Adidas", "AliExpress", "Dyson", "Nike", "Samsung", "Sephora", "Uniqlo"],
    priority: "APPLY_NOW",
    note: "Near-zero-cost gateway to many major brands; do not buy add-ons before revenue justifies them.",
  },
  {
    slug: "cj",
    name: "CJ Affiliate",
    applyUrl: "https://www.cj.com/join",
    cost: "Publisher signup",
    reach: "Large established affiliate network for brands, publishers, and creators.",
    examples: ["Retail", "Tech", "Fashion", "Travel", "Services"],
    priority: "APPLY_NOW",
  },
  {
    slug: "rakuten",
    name: "Rakuten Advertising",
    applyUrl: "https://rakutenadvertising.com/publishers/",
    cost: "Publisher signup",
    reach: "Global network with major retail, luxury, travel, and consumer brands.",
    examples: ["Etsy", "Newegg", "Luxury", "Retail", "Travel"],
    priority: "APPLY_NOW",
  },
  {
    slug: "flexoffers",
    name: "FlexOffers",
    applyUrl: "https://publisherprobeta.flexoffers.com/signup/accountInfo",
    cost: "Publisher application",
    reach: "Thousands of advertiser programs across many categories.",
    examples: ["Retail", "Finance", "Tech", "Travel", "Home"],
    priority: "OPTIONAL",
    note: "Useful as a coverage-expander after the major networks are active.",
  },
];

export type SupplierProgramEntry = {
  slug: string;
  name: string;
  kind: "DROPSHIP" | "POD" | "DIRECTORY";
  signupUrl: string;
  website: string;
  entryCost: string;
  monthlyCost: string;
  payWhenSold: boolean;
  priority: "START_FREE" | "TEST_LATER" | "PAID_LATER";
  coverage: string;
  caution?: string;
};

export const SUPPLIER_PROGRAMS: SupplierProgramEntry[] = [

  {
    slug: "petra-industries",
    name: "Petra Industries",
    kind: "DROPSHIP",
    signupUrl: "https://www.petra.com/become-a-customer",
    website: "https://www.petra.com/",
    entryCost: "Reseller application; no program fee published",
    monthlyCost: "$0 recurring program fee stated",
    payWhenSold: true,
    priority: "START_FREE",
    coverage: "15,000+ products across 60+ categories and 500 brands, with consumer electronics, cell-phone accessories, computers, gaming accessories, GPS, audio, home, security, outdoor, and more. No minimum order and direct dropshipping.",
    caution: "Requires business documentation such as Federal Tax ID, W-9, and resale certificate. Approval is required before wholesale pricing and dropship access.",
  },
  {
    slug: "cwr-wholesale",
    name: "CWR Wholesale Distribution",
    kind: "DROPSHIP",
    signupUrl: "https://cwrdistribution.com/",
    website: "https://cwrdistribution.com/",
    entryCost: "Dealer application",
    monthlyCost: "$0 FTP / website integration advertised",
    payWhenSold: true,
    priority: "START_FREE",
    coverage: "18,000+ in-stock products across 300+ brands with electronics, marine, outdoor, electrical, GPS, audio, power, communications, and related gear. No minimum order and direct drop-shipping.",
    caution: "Strongest for marine, outdoor, navigation, electrical, and specialty electronics rather than broad fashion or household inventory.",
  },
  {
    slug: "dandh",
    name: "D&H Distributing",
    kind: "DROPSHIP",
    signupUrl: "https://dandh.com/",
    website: "https://dandh.com/",
    entryCost: "Reseller application",
    monthlyCost: "No recurring program fee verified",
    payWhenSold: true,
    priority: "START_FREE",
    coverage: "Major IT and consumer-electronics distributor serving SMB, reseller, and retail channels. New-customer application includes explicit authorization for drop shipments.",
    caution: "This is a true distributor account, so business verification, tax documentation, and account approval matter more than instant app-style signup.",
  },
  {
    slug: "ingram-micro",
    name: "Ingram Micro",
    kind: "DROPSHIP",
    signupUrl: "https://www.ingrammicro.com/en-us/sign-up/sign-up",
    website: "https://www.ingrammicro.com/en-us",
    entryCost: "Reseller / customer application",
    monthlyCost: "No recurring reseller program fee verified",
    payWhenSold: true,
    priority: "START_FREE",
    coverage: "Enterprise-scale technology distribution with a very large product catalog, real-time price and availability, shipping options, catalog APIs, ordering APIs, quotes, invoices, returns, and direct-ship SKUs.",
    caution: "Best fit once Acre Era's reseller credentials are established. Some brands/SKUs require authorization and account qualification.",
  },
  {
    slug: "hypercel",
    name: "Hypercel",
    kind: "DROPSHIP",
    signupUrl: "https://www.hypercel.com/",
    website: "https://www.hypercel.com/",
    entryCost: "Wholesale account signup",
    monthlyCost: "No recurring account fee verified",
    payWhenSold: false,
    priority: "START_FREE",
    coverage: "4,000 unique mobile-accessory products with phone cases, charging, Bluetooth audio, gaming, smartwatches, power banks, cables, computer accessories, and live feeds / ecommerce integration.",
    caution: "Excellent phone-accessory and mobile-tech bench; verify fulfillment terms and whether each account can blind-ship before promising dropship behavior.",
  },
  {
    slug: "td-synnex",
    name: "TD SYNNEX",
    kind: "DROPSHIP",
    signupUrl: "https://www.tdsynnex.com/",
    website: "https://www.tdsynnex.com/",
    entryCost: "Reseller account",
    monthlyCost: "Free Standard MyShop exists; automated drop-ship is in higher MyShop tiers",
    payWhenSold: true,
    priority: "TEST_LATER",
    coverage: "Large technology-distribution ecosystem. Its MyShop program includes a free catalog/build tier, while higher tiers add customer purchasing and automatic private-label drop-shipping.",
    caution: "Do not assume the free MyShop tier includes automated dropshipping; treat it as free catalog access first and qualify paid automation separately.",
  },
  {
    slug: "cj-dropshipping",
    name: "CJdropshipping",
    kind: "DROPSHIP",
    signupUrl: "https://www.cjdropshipping.com/",
    website: "https://www.cjdropshipping.com/",
    entryCost: "$0",
    monthlyCost: "$0 basic plan",
    payWhenSold: true,
    priority: "START_FREE",
    coverage: "General products, sourcing requests, store connections, order monitoring, global fulfillment, and POD options.",
    caution: "Product, shipping, warehouse, customization, and add-on service costs still apply when used.",
  },
  {
    slug: "printful",
    name: "Printful",
    kind: "POD",
    signupUrl: "https://www.printful.com/",
    website: "https://www.printful.com/",
    entryCost: "$0",
    monthlyCost: "$0 free plan",
    payWhenSold: true,
    priority: "START_FREE",
    coverage: "Print-on-demand apparel, accessories, home goods, phone cases, and branded merchandise.",
    caution: "You pay product, fulfillment, shipping, taxes, and optional extras when an order is placed.",
  },
  {
    slug: "printify",
    name: "Printify",
    kind: "POD",
    signupUrl: "https://printify.com/",
    website: "https://printify.com/",
    entryCost: "$0",
    monthlyCost: "$0 free plan",
    payWhenSold: true,
    priority: "START_FREE",
    coverage: "Large POD marketplace with 2,000+ products and multiple print providers.",
    caution: "Free plan uses standard product pricing; paid plans mainly improve discounts and scale.",
  },
  {
    slug: "zendrop",
    name: "Zendrop",
    kind: "DROPSHIP",
    signupUrl: "https://www.zendrop.com/",
    website: "https://www.zendrop.com/",
    entryCost: "$0",
    monthlyCost: "$0 limited free plan",
    payWhenSold: true,
    priority: "START_FREE",
    coverage: "Large product catalog with a free entry tier and optional automation / branding upgrades.",
    caution: "Automated fulfillment and several growth features sit behind paid plans; do not upgrade until the economics justify it.",
  },
  {
    slug: "inventory-source",
    name: "Inventory Source Supplier Directory",
    kind: "DIRECTORY",
    signupUrl: "https://www.inventorysource.com/dropshippers/",
    website: "https://www.inventorysource.com/",
    entryCost: "$0 directory",
    monthlyCost: "$0 for directory research",
    payWhenSold: false,
    priority: "START_FREE",
    coverage: "Free directory advertising 6,500+ wholesalers and dropshippers plus supplier product information.",
    caution: "Automation and integrations can cost extra. Use the free directory for supplier discovery first.",
  },
  {
    slug: "aliexpress-awin",
    name: "AliExpress via Awin / supplier sourcing",
    kind: "DROPSHIP",
    signupUrl: "https://www.awin.com/us/publishers",
    website: "https://www.aliexpress.com/",
    entryCost: "Near $0",
    monthlyCost: "No Acre Era subscription required for affiliate discovery",
    payWhenSold: true,
    priority: "TEST_LATER",
    coverage: "Very broad global catalog; Awin currently lists AliExpress among network brands.",
    caution: "Shipping speed, product authenticity, quality, returns, and brand authorization need item-by-item qualification before Acre Era lists anything.",
  },
  {
    slug: "autods",
    name: "AutoDS",
    kind: "DROPSHIP",
    signupUrl: "https://www.autods.com/pricing/",
    website: "https://www.autods.com/",
    entryCost: "Low-cost trial",
    monthlyCost: "Paid subscription after trial",
    payWhenSold: false,
    priority: "PAID_LATER",
    coverage: "Broad automation layer for product importing, order management, sourcing, and analytics.",
    caution: "Not a permanent free option. Keep it locked until time savings or revenue clearly exceed the subscription.",
  },
];
