import type { SupplierRegistryProfile } from "./types.ts";

const observedAt = "2026-09-29";

const source = (label: string, url?: string) => ({
  label,
  url,
  observedAt,
  sourceClass: "FOUNDER_SUPPLIED_RESEARCH" as const,
  independentlyVerifiedByBuilder: false as const,
});

const sourceAt = (observedOn: string, label: string, url?: string) => ({
  label,
  url,
  observedAt: observedOn,
  sourceClass: "FOUNDER_SUPPLIED_RESEARCH" as const,
  independentlyVerifiedByBuilder: false as const,
});

export const SUPPLIER_REGISTRY_R0: readonly SupplierRegistryProfile[] = [
  {
    providerId: "cjdropshipping",
    displayName: "CJdropshipping",
    lane: "GENERAL_MERCHANDISE",
    priority: 1,
    disposition: "QUALIFY",
    qualificationState: "FREIGHT_QUOTE_PROVEN",
    apiEntitlementState: "SOURCE_REPORTED_FREE",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: true,
    customStoreApiClaim: true,
    readCapabilities: [
      "catalog.search",
      "product.read",
      "variant.read",
      "inventory.read",
      "shipping.quote",
      "delivery.estimate",
      "webhook.verify",
      "order.simulate",
    ],
    executionAuthority: "LOCKED_R0",
    riskFlags: [
      "API_POINTS_BUDGET",
      "PRODUCT_SCOPED_WEBHOOK_SUBSCRIPTIONS",
      "RETURNS_REQUIRE_NORVANA_NORMALIZATION",
    ],
    evidence: [
      source("CJdropshipping plan / supplier-watch evidence", "https://www.cjdropshipping.com/prime"),
      source("CJdropshipping developer API evidence", "https://developers.cjdropshipping.com/en/summary/"),
    ],
    notes: [
      "First general-merchandise proving adapter.",
      "Live Preview proof on 2026-09-29 established CJ authentication, catalog/product/variant/stock/origin reads, and a non-empty normalized freight quote using NORVANA_CJ_API_KEY.",
      "Do not subscribe to entire catalog; qualify selected products only.",
      "No order creation or payment authority in R0.",
    ],
  },
  {
    providerId: "banggood",
    displayName: "Banggood Dropship",
    lane: "GENERAL_MERCHANDISE",
    priority: 2,
    disposition: "QUALIFY",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "SOURCE_REPORTED_FREE",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: null,
    customStoreApiClaim: true,
    readCapabilities: [
      "catalog.search",
      "product.read",
      "inventory.read",
      "shipping.quote",
      "delivery.estimate",
      "order.simulate",
    ],
    executionAuthority: "LOCKED_R0",
    riskFlags: [
      "SKU_SPECIFIC_RETURN_RULES",
      "DROPSHIP_PROGRAM_EXCLUSIVITY_WITH_WHOLESALE_AFFILIATE_VIP",
      "DROPSHIP_FREE_SHIPPING_EXCLUSIONS_POSSIBLE",
    ],
    evidence: [
      source("Banggood dropship/API supplier-watch evidence", "https://www.banggood.com/index.php?com=dropshipcenter&t=Login&zmkm=1"),
    ],
    notes: [
      "Second general-merchandise proving adapter to prove provider neutrality.",
      "Customer-facing return policy must not blindly mirror supplier terms.",
    ],
  },
  {
    providerId: "eprolo",
    displayName: "EPROLO",
    lane: "GENERAL_MERCHANDISE",
    priority: 3,
    disposition: "QUALIFY",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "SOURCE_REPORTED_FREE",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: true,
    customStoreApiClaim: true,
    readCapabilities: [
      "catalog.search",
      "product.read",
      "inventory.read",
      "shipping.quote",
      "delivery.estimate",
      "order.simulate",
    ],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["API_ACCESS_REQUIRES_ACCOUNT_REP_DOCUMENTATION", "BRANDING_ADD_ON_NOT_FREE"],
    evidence: [
      source("EPROLO supplier-watch evidence", "https://eprolo.com/"),
      source("EPROLO API supplier-watch evidence", "https://eprolo.com/eprolo-api/"),
    ],
    notes: ["Third general-merchandise redundancy adapter."],
  },
  {
    providerId: "hypersku",
    displayName: "HyperSKU",
    lane: "GENERAL_MERCHANDISE",
    priority: 4,
    disposition: "HOLD",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "NEEDS_ACCOUNT_VERIFICATION",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: true,
    customStoreApiClaim: null,
    readCapabilities: [],
    executionAuthority: "LOCKED_R0",
    riskFlags: [
      "CUSTOM_NEXTJS_API_UNVERIFIED",
      "PRIVATE_LABEL_MOQ_SEPARATE_FROM_DROPSHIP",
      "RETURNS_REQUIRE_NORVANA_NORMALIZATION",
    ],
    evidence: [
      sourceAt("2026-10-01", "HyperSKU supplier-watch evidence", "https://www.hypersku.com/"),
    ],
    notes: [
      "Economically attractive zero-fixed-cost fulfillment candidate.",
      "Do not bind Norvana directly until a supported custom-store API/interface is proven.",
    ],
  },
  {
    providerId: "modalyst",
    displayName: "Modalyst",
    lane: "GENERAL_MERCHANDISE",
    priority: 5,
    disposition: "HOLD",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "NEEDS_ACCOUNT_VERIFICATION",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: null,
    customStoreApiClaim: null,
    readCapabilities: [],
    executionAuthority: "LOCKED_R0",
    riskFlags: [
      "CUSTOM_NEXTJS_API_UNVERIFIED",
      "FIVE_PERCENT_RETAIL_TRANSACTION_FEE",
      "FREE_PLAN_PRODUCT_LIMIT_25",
    ],
    evidence: [
      sourceAt("2026-10-01", "Modalyst free-plan supplier-watch evidence", "https://www.modalyst.co/"),
    ],
    notes: [
      "Useful U.S./Western-supplier diversification lane if direct integration entitlement is proven.",
    ],
  },
  {
    providerId: "gelato",
    displayName: "Gelato",
    lane: "POD",
    priority: 1,
    disposition: "QUALIFY",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "SOURCE_REPORTED_FREE",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: true,
    customStoreApiClaim: true,
    readCapabilities: [
      "catalog.search",
      "product.read",
      "shipping.quote",
      "delivery.estimate",
      "returns.policy.read",
      "webhook.verify",
      "order.simulate",
    ],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["POD_BUYER_REMORSE_LIMITED", "PERSONALIZED_RETURN_LIMITS"],
    evidence: [source("Gelato supplier-watch evidence", "https://www.gelato.com/")],
    notes: ["First POD qualification target; useful international production footprint."],
  },
  {
    providerId: "prodigi",
    displayName: "Prodigi",
    lane: "POD",
    priority: 2,
    disposition: "QUALIFY",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "SOURCE_REPORTED_FREE",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: true,
    customStoreApiClaim: true,
    readCapabilities: [
      "catalog.search",
      "product.read",
      "shipping.quote",
      "delivery.estimate",
      "branding.options.read",
      "order.simulate",
    ],
    executionAuthority: "LOCKED_R0",
    riskFlags: [],
    evidence: [source("Prodigi API supplier-watch evidence", "https://www.prodigi.com/print-api/")],
    notes: ["API-first secondary POD supplier."],
  },
  {
    providerId: "printful",
    displayName: "Printful",
    lane: "POD",
    priority: 3,
    disposition: "QUALIFY",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "SOURCE_REPORTED_FREE",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: true,
    customStoreApiClaim: true,
    readCapabilities: [
      "catalog.search",
      "product.read",
      "shipping.quote",
      "delivery.estimate",
      "returns.policy.read",
      "branding.options.read",
      "order.simulate",
    ],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["OPTIONAL_WAREHOUSING_OUTSIDE_ZERO_INVENTORY_DOCTRINE"],
    evidence: [source("Printful supplier-watch evidence", "https://developers.printful.com/docs/")],
    notes: ["Preferred when white-label presentation matters more than lowest base cost."],
  },
  {
    providerId: "merchize",
    displayName: "Merchize",
    lane: "POD",
    priority: 4,
    disposition: "QUALIFY",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "SOURCE_REPORTED_FREE",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: true,
    customStoreApiClaim: true,
    readCapabilities: [
      "catalog.search",
      "product.read",
      "variant.read",
      "shipping.quote",
      "delivery.estimate",
      "returns.policy.read",
      "branding.options.read",
      "order.simulate",
    ],
    executionAuthority: "LOCKED_R0",
    riskFlags: [
      "POD_BUYER_REMORSE_LIMITED",
      "BRANDING_OPTIONS_HAVE_MIXED_MOQ_REQUIREMENTS",
    ],
    evidence: [
      sourceAt("2026-10-02", "Merchize free fulfillment/API supplier-watch evidence", "https://merchize.com/pricing-page/"),
      sourceAt("2026-10-02", "Merchize custom API evidence", "https://merchize.com/api-integration/"),
    ],
    notes: [
      "API-first POD qualification target.",
      "Keep paid hosted storefront and prepaid high-MOQ branding paths outside the zero-fixed-cost lane.",
    ],
  },
  {
    providerId: "printify",
    displayName: "Printify",
    lane: "POD",
    priority: 5,
    disposition: "HOLD",
    qualificationState: "EVIDENCE_COLLECTED",
    apiEntitlementState: "NEEDS_ACCOUNT_VERIFICATION",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: true,
    customStoreApiClaim: null,
    readCapabilities: [],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["CUSTOM_API_ENTITLEMENT_AMBIGUOUS"],
    evidence: [
      source("Printify pricing entitlement ambiguity", "https://printify.com/pricing/"),
      source("Printify API documentation exists", "https://developers.printify.com/"),
    ],
    notes: [
      "Do not build a direct custom-store dependency until account-level API entitlement is proven.",
    ],
  },
  {
    providerId: "syncee",
    displayName: "Syncee",
    lane: "GENERAL_MERCHANDISE",
    priority: null,
    disposition: "EXCLUDE",
    qualificationState: "DISCOVERED",
    apiEntitlementState: "NOT_FREE_FOR_FULFILLMENT",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: null,
    noMoqClaim: null,
    customStoreApiClaim: null,
    readCapabilities: [],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["FREE_TIER_REPORTED_AS_BROWSE_ONLY"],
    evidence: [
      sourceAt("2026-10-01", "Syncee supplier-watch exclusion", "https://www.syncee.com/pricing"),
    ],
    notes: ["Free account is not treated as a usable fulfillment tier."],
  },
  {
    providerId: "zendrop",
    displayName: "Zendrop",
    lane: "GENERAL_MERCHANDISE",
    priority: null,
    disposition: "EXCLUDE",
    qualificationState: "DISCOVERED",
    apiEntitlementState: "NOT_FREE_FOR_FULFILLMENT",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: null,
    noMoqClaim: null,
    customStoreApiClaim: null,
    readCapabilities: [],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["FREE_TIER_CANNOT_PROCESS_ORDERS_WITH_LINKED_PRODUCTS"],
    evidence: [
      sourceAt("2026-10-01", "Zendrop supplier-watch exclusion", "https://www.zendrop.com/"),
    ],
    notes: ["Preserve false-free rejection."],
  },
  {
    providerId: "supliful",
    displayName: "Supliful",
    lane: "POD",
    priority: null,
    disposition: "EXCLUDE",
    qualificationState: "DISCOVERED",
    apiEntitlementState: "NOT_FREE_FOR_FULFILLMENT",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: true,
    noMoqClaim: null,
    customStoreApiClaim: null,
    readCapabilities: [],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["FREE_TIER_ORDERS_HELD_UNTIL_PAID_UPGRADE"],
    evidence: [
      sourceAt("2026-10-02", "Supliful supplier-watch exclusion", "https://supliful.com/pricing"),
    ],
    notes: ["Free design/publish access is not treated as free fulfillment."],
  },
  {
    providerId: "spocket",
    displayName: "Spocket",
    lane: "GENERAL_MERCHANDISE",
    priority: null,
    disposition: "EXCLUDE",
    qualificationState: "DISCOVERED",
    apiEntitlementState: "NOT_FREE_FOR_FULFILLMENT",
    monthlyPlatformCostClaimCents: null,
    noInventoryClaim: null,
    noMoqClaim: null,
    customStoreApiClaim: null,
    readCapabilities: [],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["FREE_OFFER_REPORTED_AS_TRIAL_ONLY"],
    evidence: [source("Spocket supplier-watch exclusion", "https://www.spocket.co/pricing-offer")],
    notes: ["Preserve rejection so Watchtower does not repeatedly rediscover it as a free fulfillment option."],
  },
  {
    providerId: "appscenic",
    displayName: "AppScenic",
    lane: "GENERAL_MERCHANDISE",
    priority: null,
    disposition: "EXCLUDE",
    qualificationState: "DISCOVERED",
    apiEntitlementState: "NOT_FREE_FOR_FULFILLMENT",
    monthlyPlatformCostClaimCents: 0,
    noInventoryClaim: null,
    noMoqClaim: null,
    customStoreApiClaim: null,
    readCapabilities: [],
    executionAuthority: "LOCKED_R0",
    riskFlags: ["FREE_TIER_REPORTED_AS_NO_PUSHED_PRODUCTS_NO_ORDERS"],
    evidence: [source("AppScenic supplier-watch exclusion", "https://appscenic.com/pricing")],
    notes: ["Free discovery/browse account is not treated as free fulfillment."],
  },
] as const;

export function getSupplierRegistryProfile(providerId: string) {
  return SUPPLIER_REGISTRY_R0.find((profile) => profile.providerId === providerId) ?? null;
}

export function getSupplierQualificationQueue(lane: "GENERAL_MERCHANDISE" | "POD") {
  return SUPPLIER_REGISTRY_R0
    .filter((profile) => profile.lane === lane && profile.disposition !== "EXCLUDE")
    .sort((a, b) => (a.priority ?? Number.MAX_SAFE_INTEGER) - (b.priority ?? Number.MAX_SAFE_INTEGER));
}
