export type PreviewProduct = {
  id: number;
  name: string;
  slug: string;
  description: string;
  price: number;
  compareAtPrice: number | null;
  niche: string;
  volumeNumber: number;
  images: string[];
  rating: number;
  reviewCount: number;
  commerceModel: string;
  imageRightsState: string;
  externalSellerName: null;
  tags: string[];
  previewOnly: true;
  accent: string;
  icon: string;
};

export const ACRE_ERA_PREVIEW_PRODUCTS: PreviewProduct[] = [
  {
    id: -101,
    name: "Daily Pantry Set",
    slug: "preview-daily-pantry-set",
    description: "A practical pantry bundle concept for repeat household shopping.",
    price: 38,
    compareAtPrice: null,
    niche: "grocery",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["everyday", "pantry", "family"],
    previewOnly: true,
    accent: "from-[#68724f] via-[#9e9869] to-[#d5c89d]",
    icon: "🥫",
  },
  {
    id: -102,
    name: "Farm Box No. 01",
    slug: "preview-farm-box-01",
    description: "Seasonal produce box concept for a future qualified local-farm route.",
    price: 46,
    compareAtPrice: null,
    niche: "produce",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["market", "produce", "local"],
    previewOnly: true,
    accent: "from-[#40533b] via-[#6d7d4b] to-[#c6a95c]",
    icon: "🥬",
  },
  {
    id: -103,
    name: "Everyday Pet Kit",
    slug: "preview-everyday-pet-kit",
    description: "A repeat-purchase pet care concept spanning treats, cleanup, and play.",
    price: 34,
    compareAtPrice: 41,
    niche: "pets",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["pets", "everyday", "repeat"],
    previewOnly: true,
    accent: "from-[#5b4e43] via-[#8a745e] to-[#cfb28c]",
    icon: "🐾",
  },
  {
    id: -104,
    name: "Family Game Night",
    slug: "preview-family-game-night",
    description: "A family-night bundle concept built around games, snacks, and easy repeat add-ons.",
    price: 58,
    compareAtPrice: null,
    niche: "family",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["family", "kids", "home"],
    previewOnly: true,
    accent: "from-[#774b3f] via-[#b06a4c] to-[#d7a467]",
    icon: "🎲",
  },
  {
    id: -105,
    name: "Skin Reset Duo",
    slug: "preview-skin-reset-duo",
    description: "A clean beauty concept for the everyday shelf without pretending a brand partnership exists.",
    price: 52,
    compareAtPrice: 64,
    niche: "beauty",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["beauty", "skincare", "self-care"],
    previewOnly: true,
    accent: "from-[#8f6f69] via-[#c69790] to-[#e5c8b5]",
    icon: "🧴",
  },
  {
    id: -106,
    name: "Creator Travel Pack",
    slug: "preview-creator-travel-pack",
    description: "A creator-tech concept combining charging, audio, and organization for life on the move.",
    price: 129,
    compareAtPrice: 149,
    niche: "tech",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["tech", "creator", "travel"],
    previewOnly: true,
    accent: "from-[#252c31] via-[#44515b] to-[#8794a0]",
    icon: "🎧",
  },
  {
    id: -107,
    name: "City Runner 02",
    slug: "preview-city-runner-02",
    description: "A $150+ footwear concept showing how premium style can live beside everyday essentials.",
    price: 168,
    compareAtPrice: 190,
    niche: "fashion",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["style", "premium", "footwear"],
    previewOnly: true,
    accent: "from-[#222424] via-[#474a46] to-[#a18b6e]",
    icon: "👟",
  },
  {
    id: -108,
    name: "Atelier Carryall",
    slug: "preview-atelier-carryall",
    description: "A premium-bag concept for testing the luxury/editorial side of Acre Era.",
    price: 890,
    compareAtPrice: null,
    niche: "fashion",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["luxury", "premium", "bag"],
    previewOnly: true,
    accent: "from-[#171512] via-[#493a2e] to-[#9b7751]",
    icon: "👜",
  },
  {
    id: -109,
    name: "Home Reset Basket",
    slug: "preview-home-reset-basket",
    description: "A practical home-care concept mixing cleaning, laundry, and household restock.",
    price: 44,
    compareAtPrice: null,
    niche: "home-decor",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["home", "everyday", "cleaning"],
    previewOnly: true,
    accent: "from-[#5e6157] via-[#8f927f] to-[#d0cdb8]",
    icon: "🧺",
  },
  {
    id: -110,
    name: "Weekend Field Kit",
    slug: "preview-weekend-field-kit",
    description: "An outdoor-life concept that can bridge trail, travel, family, and seasonal Era storytelling.",
    price: 118,
    compareAtPrice: 139,
    niche: "wellness",
    volumeNumber: 0,
    images: [],
    rating: 0,
    reviewCount: 0,
    commerceModel: "PREVIEW_ONLY",
    imageRightsState: "PREVIEW_ONLY",
    externalSellerName: null,
    tags: ["outdoor", "travel", "era"],
    previewOnly: true,
    accent: "from-[#34403b] via-[#56685c] to-[#a79267]",
    icon: "🥾",
  },
];

export const HOME_PREVIEW_PRODUCTS = ACRE_ERA_PREVIEW_PRODUCTS.slice(0, 8);
